apiVersion: v1
kind: Service
metadata:
  name: hello-openshift
  labels:
    app: hello-openshift
spec:
  selector:
    app: hello-openshift
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
